"""empty message

Revision ID: 137ed4905569
Revises: a210bcabcc2b
Create Date: 2016-09-26 17:22:28.928084

"""

# revision identifiers, used by Alembic.
revision = '137ed4905569'
down_revision = 'a210bcabcc2b'

import sqlalchemy as sa
from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('timeout', sa.Integer()))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'timeout')
    ### end Alembic commands ###
