"""empty message

Revision ID: a210bcabcc2b
Revises: 2fdabf2bae04
Create Date: 2016-08-27 17:03:21.452829

"""

# revision identifiers, used by Alembic.
revision = 'a210bcabcc2b'
down_revision = '2fdabf2bae04'

import sqlalchemy as sa
from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created', sa.DateTime(), nullable=True),
                    sa.Column('updated', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('requestlog',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created', sa.DateTime(), nullable=True),
                    sa.Column('updated', sa.DateTime(), nullable=True),
                    sa.Column('test_id', sa.Integer(), nullable=False),
                    sa.Column('client_id', sa.Integer(), nullable=False),
                    sa.Column('result', sa.Boolean(), nullable=False),
                    sa.Column('error', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
                    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requestlog')
    op.drop_table('client')
    ### end Alembic commands ###
