"""empty message

Revision ID: c91b3f952b8c
Revises: 137ed4905569
Create Date: 2016-09-26 17:32:30.571686

"""

# revision identifiers, used by Alembic.
revision = 'c91b3f952b8c'
down_revision = '137ed4905569'

import sqlalchemy as sa
from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test', 'timeout',
                    existing_type=sa.INTEGER())
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test', 'timeout',
                    existing_type=sa.INTEGER())
    ### end Alembic commands ###
